--STUDENT ID : 2019-2-60-072
--LAB NO: 03

--QUESTION 1--

SELECT BRANCH_NAME,BRANCH_CITY
FROM BRANCH
WHERE ASSETS>1000000;

--QUESTION 2--

SELECT ACCOUNT_NUMBER, BALANCE
FROM ACCOUNT
WHERE BRANCH_NAME='Downtown' or BALANCE BETWEEN 600 AND 750;

--QUESTION 3--

SELECT ACCOUNT_NUMBER
FROM ACCOUNT A,BRANCH B
WHERE A.BRANCH_NAME = B. BRANCH_NAME AND BRANCH_CITY = 'Rye';

--QUESTION 4--

SELECT LOAN_NUMBER
FROM (LOAN NATURAL JOIN BORROWER) NATURAL JOIN CUSTOMER  
WHERE  AMOUNT >=1000 AND CUSTOMER_CITY='Harrison';

--QUESTION 5--

SELECT *
FROM ACCOUNT
ORDER BY BALANCE DESC;

--QUSTION 6--

SELECT *
FROM CUSTOMER
ORDER BY CUSTOMER_CITY;

--QUESTION 7--

SELECT CUSTOMER_NAME
FROM ACCOUNT NATURAL JOIN DEPOSITOR
INTERSECT
SELECT CUSTOMER_NAME
FROM LOAN NATURAL JOIN BORROWER;

--QUESTION 8--

SELECT CUSTOMER_NAME, CUSTOMER_CITY, CUSTOMER_STREET
FROM (ACCOUNT NATURAL JOIN DEPOSITOR)NATURAL JOIN CUSTOMER
UNION
SELECT CUSTOMER_NAME,CUSTOMER_CITY, CUSTOMER_STREET
FROM (LOAN NATURAL JOIN BORROWER) NATURAL JOIN CUSTOMER;

--QUESTION 9--

SELECT CUSTOMER_NAME,CUSTOMER_CITY
FROM (LOAN NATURAL JOIN BORROWER) NATURAL JOIN CUSTOMER
MINUS
SELECT CUSTOMER_NAME,CUSTOMER_CITY
FROM (ACCOUNT NATURAL JOIN DEPOSITOR)NATURAL JOIN CUSTOMER;

--QUESTION 10--

SELECT SUM(ASSETS) AS "TOTAL ASSET"
FROM BRANCH;

--QUESTION 11--

SELECT BRANCH_NAME, AVG(BALANCE)
FROM ACCOUNT
GROUP BY BRANCH_NAME;

--QUESTION 12--

SELECT BRANCH_CITY, AVG(BALANCE)
FROM ACCOUNT NATURAL JOIN BRANCH
GROUP BY BRANCH_CITY;

--QUESTION 13--

SELECT BRANCH_NAME, MIN(AMOUNT) AS "MINIMUM AMOUNT"
FROM LOAN
GROUP BY BRANCH_NAME;

--QUESTION 14--

SELECT BRANCH_NAME, COUNT(BRANCH_NAME)
FROM LOAN
GROUP BY BRANCH_NAME; 

--QUESTION 15--

SELECT CUSTOMER_NAME,ACCOUNT_NUMBER
FROM (ACCOUNT NATURAL JOIN DEPOSITOR)NATURAL JOIN CUSTOMER
WHERE BALANCE=(SELECT MAX(BALANCE) FROM ACCOUNT);











