--QUESTION 1--
--WITHOUT SUBQUERY--

SELECT DISTINCT CUSTOMER_NAME,CUSTOMER_STREET,CUSTOMER_CITY
FROM CUSTOMER,BRANCH
WHERE CUSTOMER.CUSTOMER_CITY=BRANCH.BRANCH_CITY;

--WITH SUBQUERY--

SELECT DISTINCT CUSTOMER_NAME,CUSTOMER_STREET,CUSTOMER_CITY
FROM (SELECT BRANCH_CITY
	  FROM BRANCH) TEMP,CUSTOMER
WHERE CUSTOMER.CUSTOMER_CITY=TEMP.BRANCH_CITY;

--QUESTION 2--
--WITHOUT SUBQUERY--

SELECT DISTINCT CUSTOMER_NAME,CUSTOMER_STREET,CUSTOMER_CITY
FROM (CUSTOMER NATURAL JOIN BORROWER),BRANCH
WHERE CUSTOMER.CUSTOMER_CITY=BRANCH.BRANCH_CITY;

--WITH SUBQUERY--

SELECT DISTINCT CUSTOMER_NAME,CUSTOMER_STREET,CUSTOMER_CITY
FROM (SELECT BRANCH_CITY
	  FROM BRANCH) TEMP, CUSTOMER NATURAL JOIN BORROWER
WHERE TEMP.BRANCH_CITY=CUSTOMER.CUSTOMER_CITY;

--QUESTION 3--
--WITHOUT HAVING CLAUSE--

SELECT *
FROM(SELECT BRANCH_CITY, SUM(BALANCE)AS TOT_BAL ,AVG(BALANCE)
	 FROM ACCOUNT NATURAL JOIN BRANCH
	 GROUP BY BRANCH_CITY) TEMP
WHERE TOT_BAL<1000;

--WITH HAVING CLAUSE--
SELECT BRANCH_CITY, SUM(BALANCE) ,AVG(BALANCE)
FROM ACCOUNT NATURAL JOIN BRANCH
GROUP BY BRANCH_CITY
HAVING SUM(BALANCE)<1000;

--QUESTION 4--
--WITHOUT HAVING CLAUSE--

SELECT *
FROM(SELECT BRANCH_CITY, AVG(AMOUNT) AS AVG_AMOUNT
	FROM BRANCH NATURAL JOIN LOAN
	GROUP BY BRANCH_CITY)
WHERE AVG_AMOUNT<1500;

--WITH HAVING CLAUSE--

SELECT BRANCH_CITY, AVG(AMOUNT) AS AVG_AMOUNT
FROM BRANCH NATURAL JOIN LOAN
GROUP BY BRANCH_CITY
HAVING AVG(AMOUNT)>1500;

--QUESTION 5--
--WITHOUT ALL KEYWORD--

SELECT DISTINCT CUSTOMER_NAME,CUSTOMER_STREET,CUSTOMER_CITY
FROM (CUSTOMER NATURAL JOIN DEPOSITOR) NATURAL JOIN ACCOUNT
WHERE BALANCE = (SELECT MAX(BALANCE) FROM ACCOUNT);

--WITH ALL KEYWORD--
SELECT DISTINCT CUSTOMER_NAME,CUSTOMER_STREET,CUSTOMER_CITY
FROM (CUSTOMER NATURAL JOIN DEPOSITOR) NATURAL JOIN ACCOUNT
WHERE BALANCE >= ALL( SELECT BALANCE
				FROM ACCOUNT);
				
--QUESTION 6--
--WITH ALL KEYWORD--

SELECT CUSTOMER_NAME,CUSTOMER_STREET,CUSTOMER_CITY
FROM(CUSTOMER NATURAL JOIN BORROWER)NATURAL JOIN LOAN
WHERE AMOUNT =(SELECT MIN(AMOUNT)FROM LOAN);

--WITH ALL KEYWORD--

SELECT CUSTOMER_NAME,CUSTOMER_STREET,CUSTOMER_CITY
FROM(CUSTOMER NATURAL JOIN BORROWER)NATURAL JOIN LOAN
WHERE AMOUNT <=ALL(SELECT AMOUNT
					FROM LOAN);
					
--QUESTION 7--
--WITH IN--

SELECT DISTINCT CUSTOMER_NAME,CUSTOMER_CITY
FROM (CUSTOMER NATURAL JOIN DEPOSITOR) NATURAL JOIN ACCOUNT 
WHERE CUSTOMER_NAME IN (SELECT CUSTOMER_NAME
							FROM (CUSTOMER NATURAL JOIN BORROWER) NATURAL JOIN LOAN);

--WITH EXISTS--
SELECT DISTINCT BRANCH_NAME,BRANCH_CITY
FROM(SELECT * FROM LOAN NATURAL JOIN BRANCH) TEMP
WHERE EXISTS (SELECT BRANCH_NAME FROM ACCOUNT A
			  WHERE TEMP.BRANCH_NAME=A.BRANCH_NAME);

--QUESTION 8--
--USING NOT IN--

SELECT DISTINCT CUSTOMER_NAME,CUSTOMER_CITY
FROM (CUSTOMER NATURAL JOIN DEPOSITOR) NATURAL JOIN ACCOUNT 
WHERE CUSTOMER_NAME NOT IN (SELECT CUSTOMER_NAME
							FROM (CUSTOMER NATURAL JOIN BORROWER) NATURAL JOIN LOAN);

--USING NOT EXISTS--

SELECT DISTINCT CUSTOMER_NAME,CUSTOMER_CITY
FROM(SELECT * FROM ACCOUNT NATURAL JOIN DEPOSITOR NATURAL JOIN CUSTOMER)TEMP
WHERE NOT EXISTS(SELECT * FROM(SELECT *FROM LOAN NATURAL JOIN BORROWER)TEMP1
WHERE TEMP.CUSTOMER_NAME=TEMP1.CUSTOMER_NAME);


--QUESTION 9--
--WITHOUT WITH CLAUSE--
 
SELECT *
FROM(SELECT BRANCH_NAME, SUM(BALANCE) AS TOT_BAL,AVG(BALANCE) AS AVG_BAL 
	 FROM ACCOUNT NATURAL JOIN BRANCH
	 GROUP BY BRANCH_NAME)
WHERE TOT_BAL>AVG_BAL;
--WITH WITH CLAUSE--

WITH TEMP(BRANCH_NAME,TOT_BAL,AVG_BAL)AS
	  (SELECT BRANCH_NAME,SUM(BALANCE) AS TOT_BAL,AVG(BALANCE) AS AVG_BAL 
	 FROM ACCOUNT NATURAL JOIN BRANCH
	 GROUP BY BRANCH_NAME)
SELECT *
FROM TEMP
WHERE TOT_BAL>AVG_BAL;


--QUESTION 10--
--WITHOUT WITH CLAUSE--
SELECT*
FROM(SELECT BRANCH_NAME,SUM(AMOUNT) AS TOT_AMOUNT,AVG(AMOUNT) AS AVG_AMOUNT
	 FROM BRANCH NATURAL JOIN LOAN
	  GROUP BY BRANCH_NAME)
WHERE TOT_AMOUNT<AVG_AMOUNT;

--WITH WITH CLAUSE--

WITH TEMP(BRANCH_NAME,TOT_AMOUNT,AVG_AMOUNT)AS
		 (SELECT BRANCH_NAME,SUM(AMOUNT) AS TOT_AMOUNT,AVG(AMOUNT) AS AVG_AMOUNT
	 FROM BRANCH NATURAL JOIN LOAN
	  GROUP BY BRANCH_NAME)
SELECT *
FROM TEMP
WHERE TOT_AMOUNT<AVG_AMOUNT;

